### PR TITLE
Be more specific about removing backup of .pc files only

### LINKED ISSUE #3: gmodule-no-export-2.0.pc (from glib) is missing
In an effort to reduce the size of Docker images used for various tasks on Taskcluster, I’ve tried building Servo for Android in an container with Ubuntu packages for gstreamer. I *think* they shouldn’t be needed, since we’re using gstreamer from this repository instead. However, the build fails:

```
error: failed to run custom build command for `gstreamer-sys v0.6.0`
process didn't exit successfully: `/repo/target/debug/build/gstreamer-sys-73789ff24e121638/build-script-build` (exit code: 1)
--- stderr
`"pkg-config" "--libs" "--cflags" "gstreamer-1.0 >= 1.12"` did not exit successfully: exit code: 1
--- stderr
Package gmodule-no-export-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gmodule-no-export-2.0.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gmodule-no-export-2.0', required by 'gstreamer-1.0', not found


warning: build failed, waiting for other jobs to finish...
error: build failed
```

Indeed, `gmodule-no-export-2.0.pc` is not present `target/gstreamer/gst-build-armeabi-v7a/pkgconfig/` (although 112 other `.pc` files are). In Ubuntu, `/usr/lib/x86_64-linux-gnu/pkgconfig/gmodule-no-export-2.0.pc` is owned by the `libglib2.0-dev` package.

CC @ferjm

### PR DESCRIPTION
**Pull request by ferjm**
Fixes #3

r? @SimonSapin

### CODE REVIEW

**Comment by SimonSapin** [comment]
I don’t have write access to merge or formally mark as approved, but looks good to me. I see how this fixes #3 but out of curiosity: what is an example of file name that we do want to remove, and what creates those files in the first place?

**Comment by SimonSapin** [comment]
I don’t have write access to merge or formally mark as approved, but looks good to me. I see how this fixes #3 but out of curiosity: what is an example of file name that we do want to remove, and what creates those files in the first place?

**Comment by ferjm** [comment]
The files are created by [these](https://github.com/servo/libgstreamer_android_gen/blob/e19dbc9f1fe8bce34634371ea24ac19f20d7f046/build.sh#L39-L42) `sed` search/replace commands as backup files (i.e. `gstreamer-1.0.pc-e`). In addition to these backup files, we were accidentally removing `gmodule-export-2.0.pc`, `gmodule-no-export-2.0.pc` and `gst-editing-services-1.0.pc`.

**Comment by SimonSapin** [comment]
What I was getting at is: can we make those backup files not be created in the first place, and remove the `rm` command? It looks like a difference an argument parsing between GNU sed and BSD sed. In the latter, `-e` in these sed command is interpreted not as `--expression`, but as a suffix for `-i` that says to create backup files. So maybe removing the `-e` flags and the `rm` command would work?

**Pull request merged**
